version: "3.8"
services:
  redis:
    container_name: redis
    image: docker.io/bitnami/redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    volumes:
      - "redisinsight_data:/db"
volumes:
  redis_data:
  redisinsight_data:
