version: "3.8"
services:
  postgresql:
    container_name: postgresql
    image: docker.io/bitnami/postgresql:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    environment:
      - POSTGRESQL_USERNAME=datnt
      - POSTGRESQL_PASSWORD=111
      - POSTGRESQL_DATABASE=db
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    depends_on:
      - postgresql
    ports:
      - "8080:80"
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
    environment:
      - PGADMIN_DEFAULT_EMAIL=datnt@email.com
      - PGADMIN_DEFAULT_PASSWORD=111
volumes:
  postgresql_data:
    driver: local
  pgadmin_data:
    driver: local
