version: "3.8"
services:
  postgresql:
    container_name: postgresql
    image: docker.io/bitnami/postgresql:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    environment:
      POSTGRESQL_USERNAME: user
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: database
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    depends_on:
      - postgresql
    ports:
      - "8080:80"
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: email@example.com
      PGADMIN_DEFAULT_PASSWORD: password
volumes:
  postgresql_data:
  pgadmin_data:
