version: "3.8"
services:
  kafka:
    container_name: kafka
    image: docker.io/bitnami/mongodb:latest
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/bitnami/mongodb"
    environment:
      # for development
      # - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_ROOT_PASSWORD=root
      - MONGODB_USERNAME=usename
      - MONGODB_PASSWORD=password
      - MONGODB_DATABASE=database
volumes:
  mongodb_data:
